baseURL = 'https://pearrybyte.github.io/recordofmyyouth/'
languageCode = 'en-us'
title = 'Record Of My Youth'
theme = 'hugo-theme-re-terminal'
[caches]
  [caches.images]
    dir = ':cacheDir/images'
[params]
  customCSS = ["css/custom.css"]

  images = ["images/site-preview.jpg"]


[params.opengraph]
  image = "images/site-preview.jpg"
  image_alt = "Your Site Description"


[params.twitter]
  image = "images/site-preview.jpg"